name: Wizard101
main: me.cybersoul.Wizard101
version: Alpha v1.0
commands:
   main:
      description: Tests if the plugin is currently working!
      usage: /<command>
   commons:
      description: Teleports you to the commons!
      usage: /<command>